filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  json.keys_under_root: true
  json.message_key: log
  json.add_error_key: true
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# Send logs directly to Elasticsearch instead of through Logstash
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: "code-lab1_backend-flask"
        - equals:
            container.name: "code-lab1_frontend"

# Enable monitoring with Elasticsearch
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["elasticsearch:9200"]

# Configure logging for Filebeat itself
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Setup default index template
setup.ilm.enabled: auto
setup.ilm.rollover_alias: "filebeat"
setup.ilm.pattern: "{now/d}-000001"
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

# Enable Kibana dashboards loading
setup.kibana:
  host: "kibana:5601"
  dashboards.enabled: true